language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - "node_modules"
install:
  - npm install
before-script:
  - cypress install
script:
  - npm run cypress:run 

